# Generated by Django 4.1.7 on 2023-02-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='email',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
