# Generated by Django 4.1.7 on 2023-02-26 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_shop', '0002_remove_shopuser_email_shopuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
