# Generated by Django 4.1.7 on 2023-02-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0003_alter_shopuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description_adv', models.TimeField()),
                ('avilable', models.BooleanField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('price', models.IntegerField(null=True)),
                ('description_product', models.CharField(max_length=1500, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('tag', models.CharField(choices=[('Sport', 'Sport'), ('Dom', 'Dom'), ('Elektronika', 'Elektronika'), ('Uroda', 'Uroda'), ('Rozrywka', 'Rozrywka'), ('Odzież', 'Odzież'), ('Motoryzacja', 'Motoryzacja')], max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shopuser',
            name='address',
            field=models.TextField(default='address'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='super_shop.advertisement')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='super_shop.shopuser')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_shop.product'),
        ),
    ]
