# Generated by Django 4.1.7 on 2023-02-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0004_advertisement_product_shopuser_address_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description_adv',
            field=models.TextField(),
        ),
    ]
