# Generated by Django 4.1.7 on 2023-02-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0008_remove_product_product_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productimg',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
