# Generated by Django 4.1.7 on 2023-02-26 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0009_productimg_image_productimg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopuser',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='super_shop.shopuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='avilable',
            field=models.BooleanField(default=True, verbose_name='Czy ogloszenie ma byc aktywne'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description_adv',
            field=models.TextField(verbose_name='Tresc ogloszenia: '),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Tytul: '),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True, verbose_name='Cena:'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='image',
            field=models.ImageField(blank=True, help_text='Allowed file types: jpg, jpeg, png', null=True, upload_to='product_imgs/', verbose_name='Product Image'),
        ),
    ]
