# Generated by Django 4.1.7 on 2023-02-26 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0013_product_shopuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='shopuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='super_shop.shopuser'),
        ),
    ]
