# Generated by Django 4.1.7 on 2023-02-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0014_advertisement_shopuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='image',
            field=models.ImageField(blank=True, default='default_item.jpg', help_text='Allowed file types: jpg, jpeg, png', null=True, upload_to='product_imgs/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='super_shop.product'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='default_pic.jpg', help_text='Allowed file types: jpg, jpeg, png', null=True, upload_to='user_imgs/'),
        ),
    ]
