# Generated by Django 4.1.7 on 2023-02-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0015_alter_productimg_image_alter_productimg_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='super_shop.product'),
        ),
    ]
