# Generated by Django 4.1.7 on 2023-02-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0019_remove_productimg_product_productimg_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_item.jpg', help_text='Allowed file types: jpg, jpeg, png', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ProductImg',
        ),
    ]
