# Generated by Django 4.1.7 on 2023-03-02 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0020_product_image_delete_productimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='avilable',
            new_name='available',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='products',
            field=models.ManyToManyField(to='super_shop.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='super_shop.shopuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[(0, 'Gotówka'), (1, 'BLIK'), (2, 'Przelew')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='super_shop.shopuser'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Ilosc'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(0, 'Nowy'), (1, 'Używany')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='Tytul: '),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[(0, 'Sport'), (1, 'Dom'), (2, 'Elektronika'), (3, 'Uroda'), (4, 'Rozrywka'), (5, 'Odzież'), (6, 'Motoryzacja')], max_length=40, null=True),
        ),
    ]
